Cell 1 — Imports

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

RAW_DIR = Path("../data/raw")

pd.set_option("display.max_columns", None)

In [12]:
import sys
print(sys.executable)

c:\python314\python.exe

Cell 2 — See all datasets

In [13]:
files = list(RAW_DIR.glob("*.csv"))

for file in files:
    print(f"{file.name:25} {file.stat().st_size / (1024**2):.2f} MB")

CEAS_08.csv               64.76 MB
emails.csv                1360.06 MB
Enron.csv                 43.45 MB
Ling.csv                  8.91 MB
malicious_phish.csv       43.55 MB
Nazario.csv               7.45 MB
Nigerian_Fraud.csv        8.77 MB
phishing_email.csv        101.67 MB
spam.csv                  0.48 MB
SpamAssasin.csv           14.19 MB

Cell 3 — Inspect columns without loading everything

In [14]:
for file in files:
    print("\n" + "=" * 60)
    print(file.name)

    try:
        df_sample = pd.read_csv(
            file,
            nrows=5,
            encoding="utf-8"
        )
    except UnicodeDecodeError:
        try:
            df_sample = pd.read_csv(
                file,
                nrows=5,
                encoding="latin-1"
            )
        except Exception as e:
            print("Could not read:", e)
            continue

    print("Columns:", df_sample.columns.tolist())
    display(df_sample.head(2))

============================================================
CEAS_08.csv
Columns: ['sender', 'receiver', 'date', 'subject', 'body', 'label', 'urls']

,sender,receiver,date,subject,body,label,urls
0,Young Esposito <Young@iworld.de>,user4@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 16:31:02 -0700",Never agree to be a loser,"Buck up, your troubles caused by small dimensi...",1,1
1,Mok <ipline's1983@icable.ph>,user2.2@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 18:31:03 -0500",Befriend Jenna Jameson,\nUpgrade your sex and pleasures with these te...,1,1

============================================================
emails.csv
Columns: ['file', 'message']

                     file                                            message
0   allen-p/_sent_mail/1.  Message-ID: <18782981.1075855378110.JavaMail.e...
1  allen-p/_sent_mail/10.  Message-ID: <15464986.1075855378456.JavaMail.e...

============================================================
Enron.csv
Columns: ['subject', 'body', 'label']

,subject,body,label
0,"hpl nom for may 25 , 2001",( see attached file : hplno 525 . xls )\r\n- h...,0
1,re : nom / actual vols for 24 th,- - - - - - - - - - - - - - - - - - - - - - fo...,0

============================================================
Ling.csv
Columns: ['subject', 'body', 'label']

,subject,body,label
0,job posting - apple-iss research center,content - length : 3386 apple-iss research cen...,0
1,NaN,"lang classification grimes , joseph e . and ba...",0

============================================================
malicious_phish.csv
Columns: ['url', 'type']

                                   url      type
0                     br-icloud.com.br  phishing
1  mp3raid.com/music/krizz_kaliko.html    benign

============================================================
Nazario.csv
Columns: ['sender', 'receiver', 'date', 'subject', 'body', 'urls', 'label']

,sender,receiver,date,subject,body,urls,label
0,Mail System Internal Data <MAILER-DAEMON@monke...,NaN,28 Sep 2017 09:57:25 -0400,DON'T DELETE THIS MESSAGE -- FOLDER INTERNAL DATA,This text is part of the internal format of yo...,1,1
1,cPanel <service@cpanel.com>,jose@monkey.org,"Fri, 30 Oct 2015 00:00:48 -0500",Verify Your Account,Business with \t\t\t\t\t\t\t\tcPanel & WHM \t...,1,1

============================================================
Nigerian_Fraud.csv
Columns: ['sender', 'receiver', 'date', 'subject', 'body', 'urls', 'label']

,sender,receiver,date,subject,body,urls,label
0,MR. JAMES NGOLA. <james_ngola2002@maktoob.com>,webmaster@aclweb.org,"Thu, 31 Oct 2002 02:38:20 +0000",URGENT BUSINESS ASSISTANCE AND PARTNERSHIP,FROM:MR. JAMES NGOLA.\nCONFIDENTIAL TEL: 233-2...,0,1
1,Mr. Ben Suleman <bensul2004nng@spinfinder.com>,R@M,"Thu, 31 Oct 2002 05:10:00 -0000",URGENT ASSISTANCE /RELATIONSHIP (P),"Dear Friend,\n\nI am Mr. Ben Suleman a custom ...",0,1

============================================================
phishing_email.csv
Columns: ['text_combined', 'label']

                                       text_combined  label
0  hpl nom may 25 2001 see attached file hplno 52...      0
1  nom actual vols 24 th forwarded sabrae zajac h...      0

============================================================
spam.csv
Columns: ['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN

============================================================
SpamAssasin.csv
Columns: ['sender', 'receiver', 'date', 'subject', 'body', 'label', 'urls']

,sender,receiver,date,subject,body,label,urls
0,Robert Elz <kre@munnari.OZ.AU>,Chris Garrigues <cwg-dated-1030377287.06fa6d@D...,"Thu, 22 Aug 2002 18:26:25 +0700",Re: New Sequences Window,"Date: Wed, 21 Aug 2002 10:54:46 -0500 ...",0,1
1,Steve Burt <Steve_Burt@cursor-system.com>,"""'zzzzteana@yahoogroups.com'"" <zzzzteana@yahoo...","Thu, 22 Aug 2002 12:46:18 +0100",[zzzzteana] RE: Alexander,"Martin A posted:\nTassos Papadopoulos, the Gre...",0,1

also tell us which encoding worked

In [15]:
for file in files:
    print("\n" + "=" * 60)
    print(file.name)

    df_sample = None
    encoding_used = None

    for encoding in ["utf-8", "utf-8-sig", "cp1252", "latin-1"]:
        try:
            df_sample = pd.read_csv(
                file,
                nrows=5,
                encoding=encoding
            )
            encoding_used = encoding
            break
        except UnicodeDecodeError:
            continue
        except Exception as e:
            print(f"Other error with {encoding}: {e}")
            break

    if df_sample is None:
        print("Could not read this file")
        continue

    print(f"Encoding: {encoding_used}")
    print("Columns:", df_sample.columns.tolist())
    display(df_sample.head(2))

============================================================
CEAS_08.csv
Encoding: utf-8
Columns: ['sender', 'receiver', 'date', 'subject', 'body', 'label', 'urls']

,sender,receiver,date,subject,body,label,urls
0,Young Esposito <Young@iworld.de>,user4@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 16:31:02 -0700",Never agree to be a loser,"Buck up, your troubles caused by small dimensi...",1,1
1,Mok <ipline's1983@icable.ph>,user2.2@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 18:31:03 -0500",Befriend Jenna Jameson,\nUpgrade your sex and pleasures with these te...,1,1

============================================================
emails.csv
Encoding: utf-8
Columns: ['file', 'message']

                     file                                            message
0   allen-p/_sent_mail/1.  Message-ID: <18782981.1075855378110.JavaMail.e...
1  allen-p/_sent_mail/10.  Message-ID: <15464986.1075855378456.JavaMail.e...

============================================================
Enron.csv
Encoding: utf-8
Columns: ['subject', 'body', 'label']

,subject,body,label
0,"hpl nom for may 25 , 2001",( see attached file : hplno 525 . xls )\r\n- h...,0
1,re : nom / actual vols for 24 th,- - - - - - - - - - - - - - - - - - - - - - fo...,0

============================================================
Ling.csv
Encoding: utf-8
Columns: ['subject', 'body', 'label']

,subject,body,label
0,job posting - apple-iss research center,content - length : 3386 apple-iss research cen...,0
1,NaN,"lang classification grimes , joseph e . and ba...",0

============================================================
malicious_phish.csv
Encoding: utf-8
Columns: ['url', 'type']

                                   url      type
0                     br-icloud.com.br  phishing
1  mp3raid.com/music/krizz_kaliko.html    benign

============================================================
Nazario.csv
Encoding: utf-8
Columns: ['sender', 'receiver', 'date', 'subject', 'body', 'urls', 'label']

,sender,receiver,date,subject,body,urls,label
0,Mail System Internal Data <MAILER-DAEMON@monke...,NaN,28 Sep 2017 09:57:25 -0400,DON'T DELETE THIS MESSAGE -- FOLDER INTERNAL DATA,This text is part of the internal format of yo...,1,1
1,cPanel <service@cpanel.com>,jose@monkey.org,"Fri, 30 Oct 2015 00:00:48 -0500",Verify Your Account,Business with \t\t\t\t\t\t\t\tcPanel & WHM \t...,1,1

============================================================
Nigerian_Fraud.csv
Encoding: utf-8
Columns: ['sender', 'receiver', 'date', 'subject', 'body', 'urls', 'label']

,sender,receiver,date,subject,body,urls,label
0,MR. JAMES NGOLA. <james_ngola2002@maktoob.com>,webmaster@aclweb.org,"Thu, 31 Oct 2002 02:38:20 +0000",URGENT BUSINESS ASSISTANCE AND PARTNERSHIP,FROM:MR. JAMES NGOLA.\nCONFIDENTIAL TEL: 233-2...,0,1
1,Mr. Ben Suleman <bensul2004nng@spinfinder.com>,R@M,"Thu, 31 Oct 2002 05:10:00 -0000",URGENT ASSISTANCE /RELATIONSHIP (P),"Dear Friend,\n\nI am Mr. Ben Suleman a custom ...",0,1

============================================================
phishing_email.csv
Encoding: utf-8
Columns: ['text_combined', 'label']

                                       text_combined  label
0  hpl nom may 25 2001 see attached file hplno 52...      0
1  nom actual vols 24 th forwarded sabrae zajac h...      0

============================================================
spam.csv
Encoding: utf-8
Columns: ['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN

============================================================
SpamAssasin.csv
Encoding: utf-8
Columns: ['sender', 'receiver', 'date', 'subject', 'body', 'label', 'urls']

,sender,receiver,date,subject,body,label,urls
0,Robert Elz <kre@munnari.OZ.AU>,Chris Garrigues <cwg-dated-1030377287.06fa6d@D...,"Thu, 22 Aug 2002 18:26:25 +0700",Re: New Sequences Window,"Date: Wed, 21 Aug 2002 10:54:46 -0500 ...",0,1
1,Steve Burt <Steve_Burt@cursor-system.com>,"""'zzzzteana@yahoogroups.com'"" <zzzzteana@yahoo...","Thu, 22 Aug 2002 12:46:18 +0100",[zzzzteana] RE: Alexander,"Martin A posted:\nTassos Papadopoulos, the Gre...",0,1